[env:native]
platform = native
extra_scripts = post:scripts/native_run.py

lib_deps =
    lvgl/lvgl@9.6.0

build_flags =
    -D DASHBOARD_MODE_NATIVE=1
    -D LV_CONF_SKIP
    -D LV_USE_SDL=1
    -D LV_USE_FLOAT=1
    -D LV_FONT_MONTSERRAT_20=1
    -D LV_FONT_MONTSERRAT_28=1
    -D LV_FONT_MONTSERRAT_48=1
    !pkg-config --cflags --libs sdl2

build_src_filter =
    +<*>
    -<main_hw.cpp>

[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = arduino

platform_packages =
    platformio/framework-arduinoststm32@~4.30000.0
    platformio/tool-scons@~4.41101.0

lib_deps =
    lvgl/lvgl@9.6.0
    bodmer/TFT_eSPI@^2.5.43
    coryjfowler/mcp_can@^1.5.1

build_flags =
    -D DASHBOARD_MODE_HARDWARE=1
    -D LV_CONF_SKIP
    -D LV_USE_FLOAT=1
    -D LV_FONT_MONTSERRAT_20=1
    -D LV_FONT_MONTSERRAT_28=1
    -D LV_FONT_MONTSERRAT_48=1
    -D USER_SETUP_LOADED=1
    -D SSD1963_800_DRIVER=1
    -D TFT_PARALLEL_16_BIT=1
    -D TFT_BL=PB_0
    -D TFT_BACKLIGHT_ON=HIGH
    -D TFT_CS=PD_7
    -D TFT_DC=PD_13
    -D TFT_RST=PD_6
    -D TFT_WR=PD_5
    -D TFT_RD=PD_4
    -D TFT_D0=PA_0
    -D TFT_D1=PA_1
    -D TFT_D2=PA_2
    -D TFT_D3=PA_3
    -D TFT_D4=PA_4
    -D TFT_D5=PA_5
    -D TFT_D6=PA_6
    -D TFT_D7=PA_7
    -D TFT_D8=PC_0
    -D TFT_D9=PC_1
    -D TFT_D10=PC_2
    -D TFT_D11=PC_3
    -D TFT_D12=PC_4
    -D TFT_D13=PC_5
    -D TFT_D14=PC_6
    -D TFT_D15=PC_7
    -I$PROJECT_SRC_DIR
    -include ltoa_compat.h

build_src_filter =
    +<*>
    -<main.c>