[env:native]
platform = native

lib_deps =
    lvgl/lvgl@9.6.0

build_flags =
    -D LV_CONF_SKIP
    -D LV_USE_SDL=1
    -D LV_USE_FLOAT=1
    -D LV_FONT_MONTSERRAT_20=1
    -D LV_FONT_MONTSERRAT_28=1
    -D LV_FONT_MONTSERRAT_48=1
    !pkg-config --cflags --libs sdl2